# Linear Regression

In [1]:
import pandas as pd,numpy as np,os,sklearn
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
path = r'D:\Manipal Pro learn\Term1\EDA\Dataset'
os.chdir(path)
car = pd.read_excel('Cars.xlsx')
car.head()

manufacturer model  displ  year  cyl       trans  cty  hwy fl    class
0         audi    a4    1.8  1999    4    auto(l5)   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   16   26  p  compact

In [10]:
# Simple linear Regression

#defining x and y
X = car[['cty']]
Y = car[['hwy']]

# linear regression object

lm = LinearRegression()  #blank object

# Fitting the model

model = lm.fit(X,Y)

# Printing the value for intercept

print("Intercept value: ",lm.intercept_)  #magnitude for line of best fit
print("Coefficient value: ", lm.coef_)  # slope for line of best fit

print("simple linear expression: Y=",lm.coef_[0][0],"X + ",lm.intercept_[0])

Intercept value:  [0.8920411]
Coefficient value:  [[1.33745561]]
simple linear expression: Y= 1.3374556103369815 X +  0.8920410992333707


In [12]:
#create a validation dataset

val_data = pd.DataFrame.from_dict( {'cty' : [26]} )
val_data

cty
0   26

In [15]:
pred_highway_mileage = model.predict(val_data)
pred_highway_mileage

array([[35.66588697]])

In [16]:
drinks = pd.read_excel("Drinks.xlsx")
drinks

Day  Number of Visitors  Drinks sold
0     Monday                  32           17
1    Tuesday                  45           20
2  Wednesday                  39           23
3   Thursday                  43            7
4     Friday                  58           24
5   Saturday                  84           49
6     Sunday                  65           38

In [21]:
# Estimate how many drinks would be sold if there are 50 visitors
X= drinks[['Number of Visitors']]
Y = drinks[['Drinks sold']]
lm = LinearRegression()
drinkmodel  = lm.fit(X,Y)
# Printing the value for intercept

print("Intercept value: ",lm.intercept_)  #magnitude for line of best fit
print("Coefficient value: ", lm.coef_)  # slope for line of best fit

print("simple linear expression: Y=",lm.coef_[0][0],"X + ",lm.intercept_[0])
drinkmodel.predict(pd.DataFrame.from_dict( {'Number of Visitors' : [50]} ))

Intercept value:  [-10.19329973]
Coefficient value:  [[0.68129262]]
simple linear expression: Y= 0.6812926178476139 X +  -10.193299733175241


array([[23.87133116]])

# ML Procedure

In [37]:
# 4 step process

X = car[['cty']]
Y = car[['hwy']]

# Step1: splitting the data into training and test data

X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2) #test data to have 20% data

print(len(X_train),len(X_test),len(Y_train),len(Y_test))

# Step2: Creating model

lm1 = LinearRegression()

mlmodel = lm1.fit(X_train,Y_train)

print("Intercept value: ",lm1.intercept_)  #magnitude for line of best fit
print("Coefficient value: ", lm1.coef_)  # slope for line of best fit

print("simple linear expression: Y=",lm1.coef_[0][0],"X + ",lm1.intercept_[0])

# Step3: Predict the result for X_test

Y_test['hwy_pred'] = mlmodel.predict(X_test)

print("Accuracy by mean of predicted and actual: ",Y_test['hwy_pred'].mean()," ", Y_test['hwy'].mean())

print("Accuracy by correlation of predicted and actual: ",Y_test.corr())

# Step4: Pass validation data

mlmodel.predict(val_data)

187 47 187 47
Intercept value:  [0.70417265]
Coefficient value:  [[1.35384509]]
simple linear expression: Y= 1.3538450868532244 X +  0.7041726536825479
Accuracy by mean of predicted and actual:  23.546707842503967   23.106382978723403
Accuracy by correlation of predicted and actual:                hwy  hwy_pred
hwy       1.00000   0.97424
hwy_pred  0.97424   1.00000


C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:25: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy


array([[35.90414491]])